stages:          # List of stages for jobs, and their order of execution
  - deploy

deploy-job:      # This job runs in the deploy stage.
  stage: deploy
  tags:
    - production
  script:
    - npm install
    - npm run build
  after_script:
    - cp -r dist/* /battaglini.fr/
    - cd
    - rm -rf builds