stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:
  stage: build
  tags:
    - podman-in-podman
  script:
    - podman run -v ./frontend:/frontend docker.io/node:20.11.1-alpine /bin/bash -c "cd /frontend && npm ci && npm run build"
  after_script:
    - podman system prune -af
    - rm -rf ./frontend
  only:
    - merge_requests

deploy-job:      # This job runs in the deploy stage.
  stage: deploy
  when: manual
  tags:
    - production
  script:
    - npm install
    - npm run build
  after_script:
    - cp -r dist/* /battaglini.fr/
    - cd
    - rm -rf builds
  only:
    - main